Add a bash script to launch ganga with Python 2.7
The file which used to be `ganga` is now moved to `ganga.py` and `ganga`
is now a shell script which gets the externals' location, tries to find
Python 2.7 and then launches `ganga.py` with it.

diff --git a/bin/ganga b/bin/ganga
--- a/bin/ganga
+++ b/bin/ganga
@@ -1,57 +1,31 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-################################################################################
-# Ganga Project. http://cern.ch/ganga
-#
-# $Id: ganga,v 1.1 2008-07-17 16:40:05 moscicki Exp $
-################################################################################
+#Get the directory where this script is stored
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+    SOURCE="$(readlink "$SOURCE")"
+    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+done
+DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
-"""Executable for starting Ganga
+BASEDIR=$( dirname "${DIR}" )
 
-   If a Python script is given as argument then it is executed
-   within the Ganga environment. 
+#Add the path to the installed externals
+NEW_PYTHONPATH=`PYTHONPATH=$BASEDIR/python $DIR/ganga-external-env.py`
+export PYTHONPATH=$NEW_PYTHONPATH${PYTHONPATH:+:}${PYTHONPATH}
 
-   If no argument is given then the Python interpreter is invoked
-   within the Ganga environment"""
-
-# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-# Perform setup needed for using Ganga Public Interface (GPI)
-# This is a Copy/Paste logic which must stay in THIS file
-
-def standardSetup():
-   """Function to perform standard setup for Ganga.
-   """   
-   import sys, os.path
-
-   # insert the path to Ganga itself
-   exeDir = os.path.abspath(os.path.normpath(os.path.dirname(sys.argv[0])))
-   gangaDir = os.path.join(os.path.dirname(exeDir), 'python' )
-   sys.path.insert(0, gangaDir)
-
-   import Ganga.PACKAGE
-   Ganga.PACKAGE.standardSetup()
-
-standardSetup()
-del standardSetup
-# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-
-from Ganga.Core import GangaException
-import sys
-
-try:
-   # Process options given at command line and in configuration file(s)
-   # Perform environment setup and bootstrap
-   import Ganga.Runtime
-   Ganga.Runtime._prog = Ganga.Runtime.GangaProgram()
-   Ganga.Runtime._prog.parseOptions()
-   Ganga.Runtime._prog.configure()
-   Ganga.Runtime._prog.initEnvironment(Ganga.Runtime._prog.options.rexec)
-   Ganga.Runtime._prog.bootstrap(Ganga.Runtime._prog.interactive)
-   Ganga.Runtime._prog.new_user_wizard()
-   # Import GPI and run Ganga
-   from Ganga.GPI import *
-   Ganga.Runtime._prog.run()
-except GangaException,x:
-   Ganga.Runtime._prog.log(x)
-   sys.exit(-1)
-
+#Find a valid version of Python and run with it
+#First try the binary named 'python2.7'
+#Then check if 'python' is version 2.7
+#Finally try 'python27' from Software Collections
+if command -v python2.7 >/dev/null 2>&1; then
+    python2.7 $DIR/ganga.py $@
+elif python -c "import sys; exit(0) if sys.version_info[0:2]==(2,7) else exit(1)"; then
+    python $DIR/ganga.py $@
+elif scl --list | grep -q python27; then
+    scl enable python27 -- python $DIR/ganga.py $@
+else
+    echo 'Cannot find Python 2.7'
+    exit 1
+fi
